FROM alpine:latest

LABEL org.owasp.oshp.url="https://www.owasp.org/index.php/OWASP_Secure_Headers_Project" \
  org.owasp.oshp.name="Owasp SecureHeaders Project" \
  org.owasp.oshp.description="Front-end from SecureHeaders Project" \
  org.owasp.oshp.version="v3.1.0" \
  org.owasp.oshp.maintainer="alexandre menezes <alexandre.fmenezes@owasp.org>"

ENV APP_DIR /opt/headers
ENV FLASK_APP ${APP_DIR}/web/webui.py
ENV BRANCH_TAG master
ENV NEWRELIC_APM

ARG BRANCH=$BRANCH_TAG
ARG URL=https://github.com/oshp/headers.git

WORKDIR ${APP_DIR}

RUN apk add --no-cache py2-pip py-setuptools gcc make build-base python2-dev git \
  && git clone --depth 1 $URL -b $BRANCH . \
  && pip2 install --upgrade pip \
  && pip2 install -r requirements.txt \
  && pip2 install newrelic \
  && newrelic-admin generate-config $NEWRELIC_APM newrelic.ini

EXPOSE 5000

ADD entrypoint/docker-entrypoint.sh /docker-entrypoint.sh

ENTRYPOINT ["/docker-entrypoint.sh"]
